on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  deploy:
    name: Upload to Amazon S3
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2
    - name: git clone
      run: git remote set-url origin https://fumitrial8:${GITHUB_TOKEN}@github.com/fumitrial8/actions.git

      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}    
    - name: python run
      run: pip3 install -r requirements.txt

    - name: python run
      run: nohup python3 run.py &
