on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  deploy:
    name: Upload to Amazon ec2
    runs-on: ubuntu-18.04
    steps:

    - name: git clone
      env:
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        EC2_USER: ${{ secrets.EC2_USER }}
        EC2_HOST: ${{ secrets.EC2_HOST }}
      run: |
        echo "$SECRET_KEY" > secret_key
        chmod 600 secret_key
        echo ${EC2_USER}
        ssh -i secret_key -o StrictHostKeyChecking=no ${EC2_USER}@${EC2_HOST} "cd actions && which python && pkill gunicorn && git pull origin master && pip3 install -v -r requirements.txt && gunicorn -b :5000 run:app"
        
