on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  deploy:
    name: Upload to Amazon ec2
    runs-on: ubuntu-latest

    steps:
    - name: git clone
      env:
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        EC2_USER: ${{ secrets.EC2_USER }}
        EC2_HOST: ${{ secrets.EC2_HOST }}
      run: 
        echo "$SECRET_KEY" > secret_key
        chmod 600 secret_key
        ssh -i secret_key -o StrictHostKeyChecking=no "${EC2_USER}"@"${EC2_HOST}" "cd actions && git pull origin master"

    - name: python run
      run: pip3 install -r requirements.txt

    - name: python run
      run: nohup python3 run.py &
