on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  deploy:
    name: Upload to Amazon ec2
    runs-on: ubuntu-latest

    steps:
#     - name: Checkout
#       uses: actions/checkout@v2
#     - name: Configure AWS credentials
#       uses: aws-actions/configure-aws-credentials@v1
#       with:
#         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#         aws-region: us-east-2

    - name: git clone
      run: 
        echo "$SECRET_KEY" > secret_key
        chmod 600 secret_key
        ssh -o StrictHostKeyChecking=no ${EC2_USER}@${EC2_HOST} -i secret_key "cd /home/ubuntu && pwd && git pull origin master"
      env:
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        EC2_USER: ${{ secrets.EC2_USER }}
        EC2_HOST: ${{ secrets.EC2_HOST }}

    - name: python run
      run: pip3 install -r requirements.txt

    - name: python run
      run: nohup python3 run.py &
