on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: start
        uses: peterkimzz/aws-ssm-send-command@1.0.1
        env:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1a
          instance-ids: ${{ secrets.INSTANCE_ID }}
          working-directory: /home/ubuntu/actions/

      - name: install module
        run: pip3 install -r requirements.txt
        env:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1a
          instance-ids: ${{ secrets.INSTANCE_ID }}
          working-directory: /home/ubuntu/actions/

      - name: python run
        run: nohup python3 run.py &
